routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' =>'auth'], function()
{
    Route::get('/', function () {
        return view('admin.blank_page.index');
    });

    Route::resource('categories', '\App\Http\Controllers\CategoryController');
    Route::get('products/export-pdf', '\App\Http\Controllers\ProductController@exportPdf')->name('products.export_pdf');
    Route::get('products/export-excel', '\App\Http\Controllers\ProductController@exportExcel')->name('products.export_excel');

    Route::resource('products', '\App\Http\Controllers\ProductController');
});
Auth::routes();

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'category_id',
        'name',
        'stock',
        'image',
        'price',
        'description'
    ];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Http\Requests\ProductRequest;
use Barryvdh\DomPDF\Facade\Pdf;
use App\Exports\ProductsExport;
use Excel;
class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('admin.product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin.product.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        Product::create($request->all());
        return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $categories = Category::all();
        return view('admin.product.edit', compact('categories', 'product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, Product $product)
    {
        $product->update($request->all());
        return redirect()->route('products.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();
        // Toastr::error('Data Produk Dihapus', 'Data Deleted', ["positionClass" => "toast-top-center"]);
        return redirect()->route('products.index');
    }

    public function exportPdf()
    {
        $data = [
            'products' => Product::all()
        ];

        $pdf = Pdf::loadView('admin.product.export_pdf', $data);
        return $pdf->download('testing.pdf');
    }

    public function exportExcel()
    {
        return Excel::download(new ProductsExport, 'product.xlsx');
    }
}

resources/views/admin/product/create.blade.php
@extends('admin.layouts.app')

@section('content')

{{-- *Content Wrapper --}}
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Tambah Data Barang</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Tambah Data Barang</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">

    <!-- Default box -->
    <div class="card">
      <div class="card-header">
        <a href="{{ route('products.index') }}" class="btn btn-info">Kembali</a>

        <div class="card-tools">
          <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
            <i class="fas fa-minus"></i>
          </button>
          <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
            <i class="fas fa-times"></i>
          </button>
        </div>
      </div>
      <div class="card-body">
        <form method="post" action="{{ route('products.store') }}">
          @csrf
          {{-- name --}}
          <div class="card-body">
            <div class="form-group">
              <label for="exampleInputEmail1">Name</label>
              <input type="text" class="form-control @error('name') is-invalid @enderror"  placeholder="nama" name="name" value="{{ old('name') }}">
              @error('name')
              <div class="invalid-feedback">{{ $errors->first('name') }}</div>
              @enderror
            </div>

            {{-- kategori --}}
             <div class="form-group">
                <label for="exampleInputEmail1">kategori barang</label>
                <select name="category_id"  class="form-control @error('category_id') is-invalid @enderror"  >
                    <option value="">[ Pilih Kategori : ]</option>
                    @foreach($categories as $category)

                        <option value="{{ $category->id }}" {{ old('category_id') == $category->id ? "selected" : "" }}> {{ $category->name }} </option>

                    @endforeach
                </select>
                @error('name')

                <div class="invalid-feedback">{{ $errors->first('stock') }}</div>

                @enderror
            </div>

            {{-- STOCK --}}
            <div class="form-group">
                <label for="exampleInputEmail1">Stock</label>
                <input type="number" class="form-control @error('stock') is-invalid @enderror"  placeholder="stock" name="stock" value="{{ old('stock') }}">
                @error('stock')

                <div class="invalid-feedback">{{ $errors->first('stock') }}</div>

                @enderror
            </div>

                   {{-- harga --}}
                <div class="form-group">
                    <label for="exampleInputEmail1">price</label>
                    <input type="text" class="form-control @error('price') is-invalid @enderror"  placeholder="price" name="price" value="{{ old('price') }}">
                    @error('price')

                    <div class="invalid-feedback">{{ $errors->first('price') }}</div>

                    @enderror
                </div>

            {{-- image --}}
            <div class="form-group">
                <label for="exampleInputEmail1">image</label>
                <input type="text" class="form-control @error('image') is-invalid @enderror"  placeholder="image" name="image" value="{{ old('image') }}">

            </div>

            {{-- description --}}
            <div class="form-group">
                <label for="exampleInputEmail1">description</label>
                <textarea name="description" id="" cols="30" rows="10" class="form-control @error('description') is-invalid @enderror"> </textarea>

                @error('name')
                <div class="invalid-feedback">{{ $errors->first('description') }}</div>
                @enderror
            </div>

          </div>

          <!-- /.card-body -->

          <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </form>
      </div>
      <!-- /.card-body -->
      <div class="card-footer">
        Footer
      </div>
      <!-- /.card-footer-->
    </div>
    <!-- /.card -->

  </section>
  <!-- /.content -->
</div>
{{-- *End-content-wrapper --}}

@endsection

resources/views/admin/product/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Edit Data Barang</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Edit Data Barang</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="card">
                <div class="card-header">
                    <a href="{{ route('products.index') }}" class="btn btn-success">Kembali</a>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                </div>
                <form method="POST" action="{{ route('products.update', $product->id) }}">
                    @csrf
                    {{ method_field('PATCH') }}
                    <div class="card-body">
                        <div class="form-group">
                            <label>Nama</label>
                            <input type="text"
                                class="form-control @error('name') is-invalid
                            @enderror"
                                placeholder="Nama" name="name" value="{{ old('name', $product->name) }}">
                            @error('name')
                                <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label>Kategori Barang</label>
                            <select name="category_id" class="form-control @error('category_id') is-invalid @enderror">
                                <option value="">[ Pilih Kategori ]</option>
                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}"
                                        {{ $errors->any() ? (old('category_id') == $category->id ? 'selected' : '') : ($product->category_id == $category->id ? 'selected' : '') }}>
                                        {{ $category->name }}
                                    </option>
                                @endforeach
                            </select>
                            @error('category_id')
                                <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label>Stok</label>
                            <input type="number"
                                class="form-control @error('stock') is-invalid
                            @enderror"
                                placeholder="Stock" name="stock" value="{{ old('stock', $product->stock) }}">
                            @error('stock')
                                <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label>Gambar</label>
                            <input type="text"
                                class="form-control @error('image') is-invalid
                            @enderror"
                                placeholder="image" name="image" value="{{ old('image', $product->image) }}">
                            @error('image')
                                <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label>Harga</label>
                            <input type="number"
                                class="form-control @error('price') is-invalid
                            @enderror"
                                placeholder="price" name="price" value="{{ old('price', $product->price) }}">
                            @error('price')
                                <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
                        {{-- ! Status --}}
                        <div class="form-group">
                            <label>Deskripsi</label>
                            <textarea name="description" cols="30" rows="10"
                                class="form-control @error('description') is-invalid @enderror">{{ old('description', $product->description) }}
                            </textarea>
                            @error('description')
                                <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
                <!-- /.card-footer-->
            </div>
            <!-- /.card -->

        </section>
        <!-- /.content -->
    </div>
@endsection

resources/views/admin/product/export_excel.blade.php
<table border="1" width="100%" style="border-collapse::collapse;">
    <tr>
        <th> No </th>
        <th> Nama </th>
        <th> Stock </th>
        <th> Harga </th>
        <th> Deskripsi </th>
    </tr>
    @foreach ( $products as $index => $product )
        <tr>
            <td> {{ $index + 1 }} </td>
            <td> {{ $product->name }} </td>
            <td> {{ $product->stock }} </td>
            <td> {{ $product->price }} </td>
            <td> {{ $product->description }} </td>
        </tr>
    @endforeach
    {{-- {{ dd($products) }} --}}

</table>

resources/views/admin/product/export_pdf.blade.php
<html>
<head>
    <title>PDF</title>
</head>
<body>
    <h3 align="center"> Daftar Produk</h3>
    <table border="1" width="100%" style="border-collapse::collapse;">
        <tr>
            <th> No </th>
            <th> Nama </th>
            <th> Stock </th>
            <th> Harga </th>
            <th> Deskripsi </th>
        </tr>
        @foreach ( $products as $index => $product )
            <tr>

                <td> {{ $index + 1 }} </td>
                <td> {{ $product->name }} </td>
                <td> {{ $product->stock }} </td>
                <td> {{ $product->price }} </td>
                <td> {{ $product->description }} </td>

            </tr>
        @endforeach
        {{-- {{ dd($products) }} --}}

    </table>
</body>
</html>

resources/views/admin/product/index.blade.php
@extends('admin.layouts.app')

@section('content')

{{-- *Content Wrapper --}}
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Data Barang</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Blank Page</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">

    <!-- Default box -->
    <div class="card">
      <div class="card-header">
        <a href="{{ route('products.create') }}" class="btn btn-primary">Tambah Data</a>
        <a href="{{ route('products.export_pdf') }}" target=*_blank* class="btn btn-info">Export PDF</a>
        <a href="{{ route('products.export_excel') }}" target=*_blank* class="btn btn-light border border-dark">Export excel</a>



        <div class="card-tools">
          <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
            <i class="fas fa-minus"></i>
          </button>
          <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
            <i class="fas fa-times"></i>
          </button>
        </div>
      </div>
      <div class="card-body">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th style="width: 10px">#</th>
              <th>Nama Kategori</th>
              <th>Stok</th>
              <th>Harga</th>
              <th>Deskrips</th>
            </tr>
          </thead>
          <tbody>
            @foreach ($products as $index => $product)
              <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $product->name }}</td>
                <td>{{ $product->stock }}</td>
                <td>{{ $product->price }}</td>
                <td>{{ $product->description }}</td>
                <td class="d-flex justify-content-start ">
                  <a href="{{ route('products.edit',$product->id) }}" class="btn btn-info btn-sm ">EDIT</a>
                  <form action="{{ route('products.destroy',$product->id) }}" method="POST">
                    @csrf
                    {{ method_field('DELETE') }}
                    <button class="btn-danger btn btn-sm mx-2" type="submit"> Hapus </button>
                  </form>
                </td>
              </tr>
            @endforeach
          </tbody>
        </table>
      </div>
      <!-- /.card-body -->
      <div class="card-footer">
        Footer
      </div>
      <!-- /.card-footer-->
    </div>
    <!-- /.card -->

  </section>
  <!-- /.content -->
</div>
{{-- *End-content-wrapper --}}

@endsection